---
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
---
# Installation

## Install R
> Note: R is a programming language used by Hourglass. R must be installed for the application to work, but working knowledge of R programming is not necessary. Please see Step 1 for R installation.

For **step-by-step installation instructions**:

* Install R & rtools for Windows [link](https://datag.org/resources/documents/spring-2018/37-de-barros-installing-r-on-windows/file) 

* Install R for Mac [link](https://people.umass.edu/biep540w/pdf/HOW%20TO%20install%20R%20and%20R%20Studio%20MAC%20Users%20Fall%202020.pdf).


For **shorter installation instructions**:

* Install R
     * Follow [download link](https://cran.r-project.org/bin/) on website for your operating system. 
     * For Windows, install both R from _base_ folder and Rtools from _Rtools_ folder. 


* Install RStudio _(optional)_
     * RStudio is an integrated development environment (IDE) for R that provides an alternative interface to R.
     *  Download community/open-source version for free on website [link](https://rstudio.com/products/rstudio/download/#download).


**Troubleshooting:**

* **Error**: package or namespace load failed for 'stats' in inDL(x, as.logical(local), as.logical(now), ...):
LoadLibrary failure: The specified module could not be found.
* **Solution**: Go to where R is located and delete the .Renviron file.

## Install Desktop Application
> This step is for users who prefer to use Hourglass as a standalone application for a graphical user interface.

i. Click [here](https://github.com/kazeera/Hourglass-interface) for installation instructions.
ii. Select and download the file - exe (for Windows) or dmg (for MacOS).
iii. Open in your local Downloads folder and run the file installer by double clicking on it.

When you run Hourglass for the first time in the desktop application, it will install the R package.

## Install R package (optional)
> If you are familiar with R programming, Hourglass can be used as an R package independently. Note: It will be installed when running Hourglass application the first time.

[Click here](https://github.com/kazeera/Hourglass) for installation instructions and source code on Github.

i. Open up R console.
ii. Copy and paste this code at the >. 

```r{}
install.packages(devtools)
devtools::install_github("kazeera/Hourglass")
```
