---
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
---
# How to Use the R Package

We constructed and compiled the relevant individual data filtering functions (such as subset retrieval, imputation and outlier removal) and plotting functions (such as boxplot, heatmap, correlation matrix, survival plot visualizations) into the package.

## Installation and Usage
You may install the Hourglass R package. [Click here](https://github.com/kazeera/Hourglass) for installation instructions and source code.

Example. Prepare dataframe. Make a boxplot. Make a correlation plot.
## Dataset Object 

Similar to the structural input of many assay-based omics analysis R packages, such as struc, singleCellExperiment, .. , Hourglass takes in 3 main data files 1) numeric matrix file (sample by feature matrix), 2) row annotations (including clinical and sample descriptions), and 3) column annotations (including feature and parameter descriptions). To simplify the experience for R users with all levels of experience, this standalone R package was designed to keep accessibility in mind. Therefore, the structure of the dataset object is a list() object. 
Similar to tools that explore omics and meta data structures, Hourglass characteristically takes in three data input files as part of the dataset object:
1) numMat - numeric matrix (rows = patients/samples; columns = features/parameters), 
2) rowAnn - row annotations (clinical and sample descriptions), and 
3) colAnn - column annotations (feature and parameter descriptions). 


In R: dataset or **ds** is a **list** object. You can access the following elements using the $ operator. 

| Element Name | Description | Data Structure | Code to Access |
|:--- |:--- |:--- |:---|
| name | The name of dataset or experiment | String | ds$name | 
| mat | Numeric matrix (samples/patients as rows and features as columns) | Dataframe | ds$mat |
| rowAnn | Row annotations/metadata (describes rows or samples/patients) | Dataframe | ds$rowAnn |
| colAnn | Column annotations (describes columns or features of numeric matrix) | Dataframe | ds$colAnn |
> **Code to Access** meaning: Since the latter 3 elements are dataframes, you may access the column data nesting the $ operator and using standard R operations. Ex. ds$rowAnn returns your table, ds$rowAnn$Smoker returns the info for each row/patient/sample.
